export interface Student {
    _id?: string,
    fullname: string,
    fathername: string,
    mothername: string,
    gender: string,
    age: number,
    std: number,
    birth_date: Date,
    email: string,
    phone_number: number,
    address:string,
    city:string,
    state:string,
    zipcode: number,
}
